import { useCallback, useEffect, useRef, useState } from 'react';
import { useParams, useSearchParams } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { ArrowLeft, Download, Eye, FileDown, FileText, Grid2x2Check, Printer, RefreshCw } from 'lucide-react';
import { pdfService } from '../services/pdfService.js';
import { useCatalog } from '../hooks/useCatalogs.js';
import { useToast } from '../context/ToastContext.jsx';
import { Button } from '../components/ui/Button.jsx';
import { SegmentedControl } from '../components/ui/Controls.jsx';
import { ErrorState } from '../components/ui/EmptyState.jsx';
import { Loading } from '../components/ui/Loading.jsx';
import { downloadBlob, printPdfBlob } from '../utils/files.js';
import { formatBytes, formatNumber, pluralize } from '../utils/format.js';
import './CatalogPreviewPage.css';

/**
 * EDITOR → VISTA PREVIA → GENERAR PDF → DESCARGAR / IMPRIMIR
 * La vista previa muestra el mismo HTML que el backend convierte en PDF.
 */
export default function CatalogPreviewPage() {
  const { id } = useParams();
  const [params, setParams] = useSearchParams();
  const toast = useToast();
  const catalog = useCatalog(id);
  const [guides, setGuides] = useState(false);
  const [tab, setTab] = useState('preview');
  const [pdf, setPdf] = useState(null);
  const [generating, setGenerating] = useState(false);
  const autoGenerated = useRef(false);
  const previewFrame = useRef(null);

  const preview = useQuery({
    queryKey: ['preview', id, guides],
    queryFn: () => pdfService.previewHtml(id, { guides }),
    gcTime: 0,
    refetchOnWindowFocus: false,
  });

  useEffect(() => () => pdf?.url && URL.revokeObjectURL(pdf.url), [pdf]);

  const generate = useCallback(async () => {
    setGenerating(true);
    try {
      const { blob, filename } = await pdfService.generate(id);
      setPdf({ blob, filename, url: URL.createObjectURL(blob), createdAt: new Date() });
      setTab('pdf');
      toast.success('PDF generado correctamente');
      return blob;
    } catch (error) {
      toast.error(`${error.message} Alternativa: usa "Imprimir desde el navegador" y elige "Guardar como PDF".`, {
        title: 'No se pudo generar el PDF en el servidor',
        duration: 10000,
      });
      return null;
    } finally {
      setGenerating(false);
    }
  }, [id, toast]);

  // Desde el editor: "Generar PDF" llega con ?pdf=1
  useEffect(() => {
    if (params.get('pdf') === '1' && !autoGenerated.current) {
      autoGenerated.current = true;
      setParams({}, { replace: true });
      generate();
    }
  }, [params, setParams, generate]);

  /**
   * Alternativa sin servidor: imprime el mismo HTML de la vista previa con el
   * navegador (respeta @page en mm). En el diálogo se puede elegir "Guardar como PDF".
   */
  const printFromBrowser = () => {
    const frame = previewFrame.current;
    if (!frame?.contentWindow) {
      setTab('preview');
      toast.info('Espera a que cargue la vista previa y vuelve a intentarlo.');
      return;
    }
    frame.contentWindow.focus();
    frame.contentWindow.print();
  };

  const download = async () => {
    const blob = pdf?.blob || (await generate());
    if (blob) downloadBlob(blob, pdf?.filename || 'catalogo.pdf');
  };

  const print = async () => {
    const blob = pdf?.blob || (await generate());
    if (blob) printPdfBlob(blob);
  };

  const data = catalog.data;

  return (
    <div className="preview">
      <header className="preview__bar">
        <div className="preview__group">
          <Button variant="ghost" icon={ArrowLeft} to={`/admin/catalogos/${id}`}>
            Volver al editor
          </Button>
          {data && (
            <div className="preview__info">
              <strong>{data.name}</strong>
              <small>
                {formatNumber(data.pageWidth, 1)} × {formatNumber(data.pageHeight, 1)} mm · {pluralize(data.pages?.length ?? 0, 'página')}
              </small>
            </div>
          )}
        </div>

        <SegmentedControl
          size="md"
          value={tab}
          onChange={setTab}
          ariaLabel="Modo de vista"
          options={[
            { value: 'preview', label: 'Vista previa', icon: Eye },
            { value: 'pdf', label: 'PDF generado', icon: FileText },
          ]}
        />

        <div className="preview__group preview__group--right">
          {tab === 'preview' && (
            <Button variant="ghost" icon={Grid2x2Check} active={guides} onClick={() => setGuides((g) => !g)} tooltip="Solo en pantalla: no se imprimen">
              Márgenes
            </Button>
          )}
          <Button icon={pdf ? RefreshCw : FileDown} onClick={generate} loading={generating} variant={pdf ? 'secondary' : 'primary'}>
            {pdf ? 'Regenerar PDF' : 'Generar PDF'}
          </Button>
          <Button icon={Download} onClick={download} disabled={generating} variant={pdf ? 'primary' : 'secondary'}>
            Descargar PDF
          </Button>
          <Button icon={Printer} onClick={print} disabled={generating} tooltip="Imprime el PDF generado en el servidor">
            Imprimir
          </Button>
          {tab === 'preview' && (
            <Button
              variant="ghost"
              icon={Printer}
              onClick={printFromBrowser}
              disabled={!preview.data}
              tooltip="Sin usar el servidor: en el diálogo elige 'Guardar como PDF'"
            >
              Imprimir desde el navegador
            </Button>
          )}
        </div>
      </header>

      <main className="preview__body">
        {tab === 'preview' ? (
          preview.isLoading ? (
            <Loading label="Preparando vista previa…" />
          ) : preview.isError ? (
            <ErrorState error={preview.error} onRetry={preview.refetch} />
          ) : (
            <iframe ref={previewFrame} className="preview__frame" title="Vista previa del catálogo" srcDoc={preview.data} sandbox="allow-same-origin allow-modals" />
          )
        ) : generating && !pdf ? (
          <Loading label="Generando PDF en el servidor… puede tardar unos segundos." />
        ) : pdf ? (
          <div className="preview__pdf">
            <p className="preview__pdf-meta">
              {pdf.filename} · {formatBytes(pdf.blob.size)} · generado a partir de los datos guardados
            </p>
            <iframe className="preview__frame preview__frame--pdf" title="PDF generado" src={pdf.url} />
          </div>
        ) : (
          <div className="preview__empty">
            <FileText size={32} />
            <p>Aún no se ha generado el PDF.</p>
            <Button variant="primary" icon={FileDown} onClick={generate} loading={generating}>
              Generar PDF
            </Button>
          </div>
        )}
      </main>
    </div>
  );
}
